sudo: required

dist: xenial
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    - IMAGE_NAME=chud0/is_workday

script:
  - make test

before_deploy:
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $IMAGE_NAME:latest
  - docker tag $IMAGE_NAME $IMAGE_NAME:$TRAVIS_COMMIT
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
