sudo: required

dist: xenial
language: python

python:
  - "3.7"

services:
  - docker

install:
  - pip install -r requirements.txt

env:
  global:
    - IMAGE_NAME=chud0/is_workday

script:
  - make test

before_deploy:
  - pip install -r deploy-requirements.txt
  - python deploy/image_build.py

deploy:
  provider: script
  script: python deploy/deploy.py
  on:
    branch: master
