sudo: required

dist: xenial
language: python

python:
  - "3.7"

services:
  - docker

script:
  - make test

before_deploy:
  - docker build -t chud0/is_workday .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push chud0/is_workday
