dist: xenial
language: python

python:
  - "3.7"

services:
  - docker

before_install:
  - docker build -t chud0/is_workday .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master