version: '3'
# --------------------------------------------------
services:
  app:
    image: chud0/is_workday:latest
    container_name: app
    restart: unless-stopped
    command: python app/main.py
    networks:
      - app-network
    volumes:
      - ./local:/home/app/local

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
# --------------------------------------------------
#Docker Networks
networks:
  app-network:
    driver: bridge

